### ISSUE TITLE
[FEATURE] Provide a System for Creating Reusable Style Themes

### ISSUE THREAD

**Issue by amrutha97** [StructuredLabs/preswald#534]
### Goal  
Introduce first-class support for defining and applying **reusable UI themes** across Preswald apps. Themes should encapsulate colors, typography, component styles, and layout options—allowing users to quickly standardize the look and feel of dashboards.

---

### 📌 Motivation

Preswald currently supports per-project branding via `preswald.toml`, but there is no way to:

- Define shared, named design themes
- Reuse styles across multiple apps
- Switch between dark/light themes or custom palettes
- Apply company-specific design standards consistently

Adding theme support would:
- Improve design consistency
- Speed up onboarding for teams
- Enable community-contributed themes (e.g., Tailwind/Material lookalikes)
- Make apps feel polished out of the box

---

### ✅ Acceptance Criteria

- [ ] Add a `[theme]` section in `preswald.toml` or reference external theme files
- [ ] Theme configuration includes:
  - `primaryColor`, `secondaryColor`, `fontFamily`
  - `borderRadius`, `shadow`, `spacingScale`
  - `componentOverrides` (e.g. table, button, card)
- [ ] Themes live in:  
  `preswald/themes/*.toml` or `preswald/themes/*.json`
- [ ] Expose a CLI command to list or apply a theme:
  ```bash
  preswald theme apply dark-mode
  ```
- [ ] Apply theme via Tailwind CSS configuration in frontend
- [ ] Provide default themes: `light`, `dark`, `minimal`, `preswald-orange`

---

#### 1. Example Theme File (`themes/dark-mode.toml`)

```toml
[theme]
name = "dark-mode"
primaryColor = "#F97316"
backgroundColor = "#111827"
textColor = "#F3F4F6"
fontFamily = "Inter, sans-serif"
borderRadius = "0.75rem"

[theme.components.table]
striped = true
borderColor = "#1F2937"
```

#### 2. In `preswald.toml`

```toml
[branding]
theme = "dark-mode"
```

#### 3. Frontend Integration

- Load active theme into global context
- Apply Tailwind CSS classes dynamically (or via CSS variables)
- Add utility hook: `useTheme()`

---

### 🧪 Testing Plan

- Create multiple themes: `light`, `dark`, `high-contrast`
- Launch same `hello.py` with different themes
- Validate:
  - Theme affects all UI elements
  - Overrides work at component level (e.g. buttons look different)
  - Live reload support (optional)

---

### 📚 Docs To Add

- [ ] `docs/style/themes.mdx`
- [ ] Example `themes/` folder with 2+ themes
- [ ] CLI reference: `preswald theme list`, `preswald theme apply`

---

### 🧩 Related Files

- `preswald.toml`
- `preswald/themes/*.toml`
- `frontend/src/config/theme.js`
- `tailwind.config.js`
